// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    About: typeof import('./components/About.vue')['default']
    Contact: typeof import('./components/Contact.vue')['default']
    Footer: typeof import('./components/Footer.vue')['default']
    Header: typeof import('./components/Header.vue')['default']
    IIcRoundModeNight: typeof import('~icons/ic/round-mode-night')['default']
    IMdiArrowUp: typeof import('~icons/mdi/arrow-up')['default']
    IMdiClose: typeof import('~icons/mdi/close')['default']
    IMdiDevTo: typeof import('~icons/mdi/dev-to')['default']
    IMdiGithub: typeof import('~icons/mdi/github')['default']
    IMdiLaunch: typeof import('~icons/mdi/launch')['default']
    IMdiLinkedin: typeof import('~icons/mdi/linkedin')['default']
    IMdiMedium: typeof import('~icons/mdi/medium')['default']
    IMdiMenu: typeof import('~icons/mdi/menu')['default']
    IMdiStackOverflow: typeof import('~icons/mdi/stack-overflow')['default']
    IMdiTranslate: typeof import('~icons/mdi/translate')['default']
    IMdiWhiteBalanceSunny: typeof import('~icons/mdi/white-balance-sunny')['default']
    Navbar: typeof import('./components/Navbar.vue')['default']
    ProgressBar: typeof import('./components/ProgressBar.vue')['default']
    Projects: typeof import('./components/Projects.vue')['default']
    ProjectsContainer: typeof import('./components/ProjectsContainer.vue')['default']
    README: typeof import('./components/README.md')['default']
    ScrollToTop: typeof import('./components/ScrollToTop.vue')['default']
    Skills: typeof import('./components/Skills.vue')['default']
  }
}

export { }
